### ISSUE TITLE
top nav menu items

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/CFN#1]
Should read as follows: About / fishermen / resources / News

Please pull contact and accompanying green box

**Comment by sarahmagrish** [comment]
Hi laura, Realized that "Fishermen" may be wrong. Should it read "our people" instead?

**Comment by ldford** [comment]
Correction:
About / Fishermen [plural] / Resources / News

Thanks

**Comment by ldford** [comment]
Let's stick with Fishermen for now and see how it goes

**Comment by sarahmagrish** [comment]
got it - final word here James: 

Should read as follows: About / fisherman / resources / News

Please pull contact and accompanying green box

**Comment by ghost** [comment]
What about "Events" ?

**Comment by ghost** [comment]
Also - just to confirm - it's "fishermen" (plural) NOT "fisherman" singular, right?

**Comment by ldford** [comment]
Jim, please drop Events entirely from top nav. YES: fishermen (plural)
