### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/CFN#3]
Georgia feels good - let's let it stay but swap out Roboto with Knockout (via our existing typography.com subscription - lmk if you need that info). 

Junior Featherweight - http://www.typography.com/fonts/knockout/webfonts/knockout-28/ - is probably a good approximation for the top nav and other Roboto condensed instances, and Junior Middleweight http://www.typography.com/fonts/knockout/webfonts/knockout-31/ for non-condensed. 

lmk if you need more detail!

**Comment by ghost** [comment]
Okay. I think I got it setup right - but, we'll need to adjust the font-size now that we are using a different font.

http://fbb.416.myftpupload.com/

**Comment by ldford** [comment]
Yeah - we need some tweaking. The top nav font is scrunched - not sure what that one is. If we increase size, will it take care of the problem? 

On a blog post (e.g. http://fbb.416.myftpupload.com/from-boat-to-table/), I see a couple issues. One, the left sidebar copy is illegible - definitely needs to be larger. 

Two, I don't think the titles need to be all caps (From Boat to Table). Too many all caps in general on the page, and this one change to the title would make a huge difference I think. Can we change that?

**Comment by ghost** [comment]
Yes. We can. I agree with both those things on the blog.

As for the navigation, I made the font a little bigger. Is that better now? Or should it be even bigger?  Maybe the navigation should be in all caps?

**Comment by ldford** [comment]
Nav font still needs to be bigger. Yes - perhaps all caps is the way to go there.

**Comment by ghost** [comment]
Okay - let me know what you think of it now. (push reload a few times)

Too big now that it is all caps?
I made the drop-downs NOT all caps and slightly smaller. So let me know what you think of that too.

**Comment by ldford** [comment]
I like the drop-downs not all caps. Looks good.

Top nav: Looks so different on different browsers! If everyone used chrome, I'd say to leave as is. But both IE and mozilla are a bit large. Let's take the top nav down a little. (drop-downs seem fine)

**Comment by ghost** [comment]
Are y'all seeing what I'm seeing?

http://cloud.krillwebdesign.com/image/0I1d140w2S2r

I have no idea what happened to the Knockout font, but that looks really funky. I'll be looking into it.

**Comment by ldford** [comment]
Did you already fix it? Not looking like that to me…

**Comment by ghost** [comment]
I think this is fixed and can be closed - please confirm.

**Comment by ldford** [comment]
I'm pretty sure this is perfect. Question: do we have to have a slider at the top? Can we opt for just one photo if we want to?

**Comment by ldford** [comment]
Yes.
