### ISSUE TITLE
About page template

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/CFN#4]
worth exploring this template here: http://make-lemonade.co/themes/kause/charity/timeline.html#?

it is pretty cool!

**Comment by sarahmagrish** [comment]
hi @ldford! should we add this to what James is scoping? or too weird?

**Comment by ldford** [comment]
sorry forgot about this. James actually talked to me about that timeline thing. It's a weird category withing Kause. I don't think it's something we are going to want to use for CFN
