### ISSUE TITLE
Footer edits

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/CFN#7]
Four small items here:
1. Could we add the mission field back in from the theme? 
   http://make-lemonade.co/themes/kause/charity/index.html
2. Could we add a title above the footer list:

Home
About
News
Contact

that reads "Keep in Touch" for now - we can edit later right? 
1. Can we pull the text "Email address:" as it is redundant
2. Finally, could we shuffle the order so it goes: MIssion, Newsletter, Keep in Touch, Member links, and login?

thx!

**Comment by ghost** [comment]
Okay. 

This is setup. You can alter the titles of the sections, and the mission text, but visiting Appearance -> Widgets and then look for Footer Widget Areas.

![widgets_ _community_fisheries_network_ _wordpress](https://cloud.githubusercontent.com/assets/886931/6378064/83a34766-bcdd-11e4-8f7f-ad3b4d3994e7.png)
