### ISSUE TITLE
Member detail page

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/CFN#8]
Hi Jim, Can we use this template for the Member detail page: http://make-lemonade.co/themes/kause/charity/about.html

 and insert an image slider like the one below with captions added?
![screen shot 2015-02-10 at 5 41 09 pm](https://cloud.githubusercontent.com/assets/4765127/6140406/1ecf385a-b14c-11e4-873f-ff6feb9b9564.png)

**Comment by ghost** [comment]
Okay - I think I need a little more explanation here, @ldford 

By "Member detail page" is @sarahmagrish referring to individual Fishermen pages?  I can't seem to remember what we had discussed and if something is missing that I need to setup.

Right now, when I go to the Fishermen page (which was called Members) I see three members:
Alaska Jig Association, Alaska Longline Fishermen's Association, and test

You can click on these to go to individual detail pages - are these what you mean by member detail page?

And if so, Is there really going to be enough on each one for a full slider, paragraphs of content, and a sidebar?

**Comment by ldford** [comment]
Jim - Yes, it's the individual Fishermen pages. I will send you a pdf comp that Sarah mocked up that gives you an idea of what we are looking for. The comp isn't exactly the style we need, but it gives you the idea of the assets we will have on hand, including hi-res photos. 

Each fishermen page will have: title of organization, 350-500 word story; 40-100 word description of organization (that's in the "About"); photos; possible addition of video; quotes; contact info; lists of all "fishermen" in the sidebar shown as logos. (in comp, they are called "members"). PDF coming.

**Comment by ghost** [comment]
Okay. Got it.

I've set it up the following way:
- It uses a revolution slider if you enter a slider slug (identifier) into a custom field for that person (fisherman).  So you have to create the slider with captions, and then attach it to the person post.
- There are new "About" and "Contact" fields on each "people" post so you can add that sidebar content in for each fisherman.  
- The Fishermen list below on the sidebar is auto populated with all people. It hasn't been filtered by a People category (are you going to use those?) So it just lists all people currently in the People custom post type.  It displays the featured image unless there is none, then it just displays the title of the person post.  I would suggest going through the "People" custom post type and removing all of the placeholder content that came with Kause. And, if there are going to be multiple categories of people (i.e. "Fishermen" and "Members" or something) I'll need to filter this list to just show a specific category. And we'll need to set those categories up.

Let me know what you think and if this works.

**Comment by ghost** [comment]
*Ping

Did I get this right?

**Comment by ldford** [comment]
YES! This is beautiful. About the "People" list: this will include all of our Members here (http://www.communityfisheriesnetwork.org/members.html) which we are calling "Fishermen" on this website. So I don't think a filter is needed. I don't think anyone will be listed in People unless they are a Fisherman (ie member of CFN). That said, you will also see on that webpage 3 organizations called "Supporting Members". That would be the only filter we might need. However, my vote is to include these inside the About pages, and keep them off of the Fishermen/Members section of the site. So for now, let's keep it as is.

**Comment by ghost** [comment]
So can we close this issue?
